#pod template used for local development and testing

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    environment: minikube
  name: timestamp-api
spec:
  containers:
  - name: timestamp-api 
    image: example/timestamp 
    imagePullPolicy: Always
    ports:
      - containerPort: 8080
    resources:
      requests:
        cpu: 0.5
        memory: 128Mi
      limits:
        cpu: 1
        memory: 256Mi
  restartPolicy: Never
